security:
    password_hashers:
        App\Entity\Utilisateur: 'auto' # L'auto fait le choix du bon algorithme de hachage

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email  # Le champ utilisé pour identifier l'utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: /connexion
                check_path: /connexion
                username_parameter: email   # Le champ dans le formulaire pour l'email
                password_parameter: motDePasse  # Le champ dans le formulaire pour le mot de passe
                enable_csrf: true
                csrf_token_id: authenticate  # Ajoute cette ligne
                default_target_path: /accueil
            logout:
                path: /deconnexion
                target: /accueil

    access_control:
        # Règles d'accès, par exemple :
        # - { path: ^/profile, roles: ROLE_USER }
